name: pymultifit
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - custom-inherit
  - Deprecated
  - pip
  - pip:
      - plotez
      - pymultifit
