name: multifit
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - matplotlib
    - scipy
    - statsmodels
    - custom-inherit
    - Deprecated
    - seaborn
    - pandas
    - pytest
    - pytest-cov
    - astropy
    - jupyter
    - notebook
    - memory_profiler
    - sphinx
    - docutils<0.21
    - sphinx-rtd-theme
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-napoleon
    - numpydoc
    - nbsphinx
    - nbsphinx-link
    - sphinx-gallery
    - sphinx-autobuild
    - mypy
    - nox
    - uv
    - types-deprecated
    - pylint
    - black
    - python-build
    - pip
    -   pip:
            - mpyez
