name: multifit
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - matplotlib
    - pillow=12.1.1
    - scipy
    - custom-inherit
    - Deprecated
    - tqdm
    - pip
    -   pip:
            - mpyez
