[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymultifit"
description = "A library to fit data with multiple fitters."
authors = [{ name = "Syed Ali Mohsin Bukhari", email = "syedali.b@outlook.com" }]

readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license-files = ["LICENSE"]
dynamic = ["version"]
dependencies = [
    "custom-inherit",
    "deprecation",
    "matplotlib",
    "numpy",
    "plotez",
    "scipy",
    "statsmodels",
    "types-deprecated"
]
keywords = ["fitting", "multi-modal", "gaussian", "lognormal", "skew", "curve fitting", "scipy"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics"
]

[tool.setuptools.dynamic]
version = { attr = "pymultifit.version.__version__" }

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["examples", "*tests*"]

[project.urls]
Homepage = "https://readthedocs.pymultifit.com"
Issues = "https://github.com/syedalimohsinbukhari/pymultifit/issues"
Repository = "https://github.com/syedalimohsinbukhari/pyMultiFit/"

# -- uv ------------------------------------------------------------------------

[tool.uv]
default-groups = ["dev"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "seaborn",
    "pandas",
    "astropy",
    "jupyter",
    "notebook",
    "build",
    "memory_profiler",
    "sphinx",
    "docutils<0.21",
    "sphinx-rtd-theme",
    "pydata-sphinx-theme",
    "sphinx-copybutton",
    "sphinxcontrib-napoleon",
    "numpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "sphinx-gallery",
    "sphinx-autobuild",
    "black[jupyter]",
    "pylint",
    "isort",
    "mypy",
    "nox",
    "uv",
    "tqdm",
    "pyqt6",
]

# -- black ---------------------------------------------------------------------

[tool.black]
line-length = 120
target-version = ["py310", "py311", "py312"]
include = '\.pyi?$'

# -- isort ---------------------------------------------------------------------

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["pymultifit"]
known_third_party = ["numpy", "matplotlib", "scipy", "plotez", "tqdm"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

# -- mypy ----------------------------------------------------------------------

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
