name: Run tests and upload coverage

on:
    push:
        branches-ignore:
            - doc

jobs:
    test:
        name: Run tests and collect coverage
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Set up Python
                uses: actions/setup-python@v4

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt pytest pytest-cov

            -   name: Test with pytest
                run: |
                    pytest --cov --junitxml=junit.xml -o junit_family=legacy

            -   name: Run tests
                run: pytest --cov --cov-report=xml

            -   name: Upload results to Codecov
                if: ${{ !cancelled() }}
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}

            -   name: Upload test results to Codecov
                if: ${{ !cancelled() }}
                uses: codecov/test-results-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
